<paste log output from Kubernetes-mediated prediction, here>
$ ./run_kubernetes.sh
nguyenanhduy032/project4:latest
Error from server (AlreadyExists): pods "predict" already exists
NAME         READY   STATUS    RESTARTS   AGE
dsadsa-app   1/1     Running   0          33s
predict      1/1     Running   0          10s
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000
[2023-05-13 10:58:02,546] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2023-05-13 10:58:02,546] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2023-05-13 10:58:02,546] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2023-05-13 10:58:02,546] INFO in app: prediction:
[20.35373177134412]
172.17.0.1 - - [13/May/2023 10:58:00] "POST /predict HTTP/1.1" 200 -